const state={theme:localStorage.getItem('z-theme')||'light',cardTheme:'theme-white',data:{card_id:null,phone_number:'+966 50 000 0000',name:'Sara Al-Harbi',title:'Senior Graphic Designer',photo:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=500&q=85',bio:'Passionate graphic designer creating modern visual identities, branding systems and digital experiences.',social_links:{whatsapp:'966500000000',instagram:'instagram.com/sara',linkedin:'linkedin.com/in/sara',website:'sara.design'},portfolio:'behance.net/sara',status:'draft',created_at:null,updated_at:null}};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
function applyTheme(){document.documentElement.dataset.theme=state.theme;const b=$('#themeToggle');if(b)b.textContent=state.theme==='dark'?'☾':'☼';localStorage.setItem('z-theme',state.theme)}
function setText(id,value){const el=$(id);if(el)el.textContent=value||''}
function syncCard(){setText('#previewName',state.data.name);setText('#previewTitle',state.data.title);setText('#previewBio',state.data.bio);const img=$('#previewImage');if(img&&state.data.photo)img.src=state.data.photo;const card=$('#liveCard');if(card){card.classList.remove('theme-white','theme-gold','theme-glass','theme-dark');card.classList.add(state.cardTheme)}}
function bindInputs(){const map={fullName:'name',jobTitle:'title',phone:'phone_number',profilePhoto:'photo',shortBio:'bio',whatsapp:'whatsapp',instagram:'instagram',linkedin:'linkedin',website:'website',portfolio:'portfolio'};Object.entries(map).forEach(([id,key])=>{const el=$('#'+id);if(!el)return;el.addEventListener('input',()=>{if(['whatsapp','instagram','linkedin','website'].includes(id))state.data.social_links[key]=el.value;else state.data[key]=el.value;syncCard();const s=$('#previewStatus');if(s)s.textContent='Unsaved changes'})})}
function makeCardId(){return 'z_'+Math.random().toString(36).slice(2,9)+'_'+Date.now().toString(36)}
function publicCardUrl(){return `${location.origin}${location.pathname}?card=${state.data.card_id||'demo'}`}
async function shareCard(){const url=publicCardUrl();if(navigator.share){try{await navigator.share({title:`${state.data.name} — Z Card`,text:'Connect with me on Z Card',url})}catch(e){}}else await copyText(url)}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('Card link copied')}catch(e){toast('Copy is not available in this browser')}}
function qrUrl(){return `https://quickchart.io/qr?text=${encodeURIComponent(publicCardUrl())}&size=220&margin=1`}
function openQr(){const modal=$('#successModal');$('.modal-card-slot',modal).innerHTML=`<div class="qr-preview"><img src="${qrUrl()}" alt="Z Card QR Code" width="180" height="180"><p class="tiny-note">Scan to open this card link.</p></div>`;modal.classList.add('show');modal.setAttribute('aria-hidden','false')}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
function createCard(e){e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;state.data.card_id=state.data.card_id||makeCardId();state.data.status='published';state.data.created_at=state.data.created_at||new Date().toISOString();state.data.updated_at=new Date().toISOString();localStorage.setItem('z-personal-card',JSON.stringify(state.data));syncCard();const modal=$('#successModal');$('.modal-card-slot',modal).innerHTML=`<div class="success-card-summary"><strong>${state.data.name}</strong><span>${state.data.title}</span><small>${state.data.phone_number}</small><code>${publicCardUrl()}</code></div>`;modal.classList.add('show');modal.setAttribute('aria-hidden','false');toast('Your Z Card is ready')}
function loadSaved(){const saved=localStorage.getItem('z-personal-card');if(saved){try{state.data=Object.assign(state.data,JSON.parse(saved));const fields={fullName:state.data.name,jobTitle:state.data.title,phone:state.data.phone_number,profilePhoto:state.data.photo,shortBio:state.data.bio,whatsapp:state.data.social_links?.whatsapp||'',instagram:state.data.social_links?.instagram||'',linkedin:state.data.social_links?.linkedin||'',website:state.data.social_links?.website||'',portfolio:state.data.portfolio||''};Object.entries(fields).forEach(([id,v])=>{const el=$('#'+id);if(el)el.value=v});syncCard()}}catch(e){}}}
function scrollTopOnUp(){let last=window.scrollY;window.addEventListener('scroll',()=>{const nav=$('#nav');if(nav)nav.classList.toggle('scrolled',window.scrollY>20);const dir=window.scrollY<last;document.body.classList.toggle('scroll-up',dir);last=window.scrollY},{passive:true})}
function bindActions(){document.addEventListener('click',async e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(action==='copy')await copyText(publicCardUrl());if(action==='share')await shareCard();if(action==='qr')openQr();const scroll=e.target.closest('[data-scroll]')?.dataset.scroll;if(scroll){const target=$('#'+scroll);if(target)target.scrollIntoView({behavior:'smooth'})};const close=e.target.closest('[data-close]')?.dataset.close;if(close){const m=$('#'+close);m.classList.remove('show');m.setAttribute('aria-hidden','true')}});document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal.show').forEach(m=>m.classList.remove('show'))})}
function bindTheme(){const b=$('#themeToggle');if(b)b.addEventListener('click',()=>{state.theme=state.theme==='dark'?'light':'dark';applyTheme()})}
function bindCardThemes(){ $$('[data-card-theme]').forEach(b=>b.addEventListener('click',()=>{$$('[data-card-theme]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.cardTheme=b.dataset.cardTheme;syncCard()})) }
function bindTabs(){ $$('.form-tabs button').forEach(b=>b.addEventListener('click',()=>{$$('.form-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.body.classList.toggle('preview-mode',b.dataset.tab==='preview')})) }
window.ZCardAPI={async createCard(payload){return {card_id:makeCardId(),status:'published',...payload}}};
document.addEventListener('DOMContentLoaded',()=>{applyTheme();loadSaved();bindInputs();bindActions();bindTheme();bindCardThemes();bindTabs();scrollTopOnUp();const f=$('#cardForm');if(f)f.addEventListener('submit',createCard);syncCard()});
